{
    "GET /livros": "GET/livros/get",
    "POST /livros": "POST/livros/create",
    "PUT /livros": "PUT/livros/update",
    "DELETE /livros": "DELETE/livros/delete",
    "GET /gibi": "GET/gibi/get",
    "POST /gibi": "POST/gibi/create",
    "PUT /gibi": "PUT/gibi/update",
    "DELETE /gibi": "DELETE/gibi/delete",
    "GET /manga": "GET/manga/get",
    "POST /manga": "POST/manga/create",
    "PUT /manga": "PUT/manga/update",
    "DELETE /manga": "DELETE/manga/delete",
    "GET /usuarios": "GET/usuarios/get",
    "POST /usuarios": "POST/usuarios/create",
    "PUT /usuarios": "PUT/usuarios/update",
    "DELETE /usuarios": "DELETE/usuarios/delete",
    "GET /blog": "GET/blog/get",
    "POST /blog": "POST/blog/create",
    "PUT /blog": "PUT/blog/update",
    "DELETE /blog": "DELETE/blog/delete",
    "GET /enderecos": "GET/enderecos/get",
    "POST /enderecos": "POST/enderecos/create",
    "PUT /enderecos": "PUT/enderecos/update",
    "DELETE /enderecos": "DELETE/enderecos/delete"
  }